# Tiny hand-curated corpus (plan §4.5) for fast dev and tests:
# a demo user plus ~50 kanji, ~110 words, and a few hundred sentences.
# Idempotent: safe to run any number of times.

# --- Kanji metadata: character => { grade, freq_rank, radical, onyomi, kunyomi, meaning } ---
KANJI = {
  "一" => { grade: 1, freq: 1, radical: "一", on: [ "いち", "いつ" ], kun: [ "ひと" ], meaning: "one" },
  "二" => { grade: 1, freq: 2, radical: "二", on: [ "に" ], kun: [ "ふた" ], meaning: "two" },
  "三" => { grade: 1, freq: 3, radical: "一", on: [ "さん" ], kun: [ "み" ], meaning: "three" },
  "四" => { grade: 1, freq: 4, radical: "囗", on: [ "し" ], kun: [ "よ", "よん" ], meaning: "four" },
  "五" => { grade: 1, freq: 5, radical: "二", on: [ "ご" ], kun: [ "いつ" ], meaning: "five" },
  "六" => { grade: 1, freq: 6, radical: "八", on: [ "ろく" ], kun: [ "む" ], meaning: "six" },
  "七" => { grade: 1, freq: 7, radical: "一", on: [ "しち" ], kun: [ "なな" ], meaning: "seven" },
  "八" => { grade: 1, freq: 8, radical: "八", on: [ "はち" ], kun: [ "や" ], meaning: "eight" },
  "九" => { grade: 1, freq: 9, radical: "乙", on: [ "きゅう", "く" ], kun: [ "ここの" ], meaning: "nine" },
  "十" => { grade: 1, freq: 10, radical: "十", on: [ "じゅう" ], kun: [ "とお" ], meaning: "ten" },
  "日" => { grade: 1, freq: 11, radical: "日", on: [ "にち", "じつ" ], kun: [ "ひ", "か" ], meaning: "day, sun" },
  "月" => { grade: 1, freq: 12, radical: "月", on: [ "げつ", "がつ" ], kun: [ "つき" ], meaning: "moon, month" },
  "火" => { grade: 1, freq: 13, radical: "火", on: [ "か" ], kun: [ "ひ" ], meaning: "fire" },
  "水" => { grade: 1, freq: 14, radical: "水", on: [ "すい" ], kun: [ "みず" ], meaning: "water" },
  "木" => { grade: 1, freq: 15, radical: "木", on: [ "もく", "ぼく" ], kun: [ "き" ], meaning: "tree, wood" },
  "金" => { grade: 1, freq: 16, radical: "金", on: [ "きん", "こん" ], kun: [ "かね" ], meaning: "gold, money" },
  "土" => { grade: 1, freq: 17, radical: "土", on: [ "ど", "と" ], kun: [ "つち" ], meaning: "earth, soil" },
  "年" => { grade: 2, freq: 18, radical: "干", on: [ "ねん" ], kun: [ "とし" ], meaning: "year" },
  "大" => { grade: 1, freq: 19, radical: "大", on: [ "だい", "たい" ], kun: [ "おお" ], meaning: "big, large" },
  "小" => { grade: 1, freq: 20, radical: "小", on: [ "しょう" ], kun: [ "ちい", "こ" ], meaning: "small" },
  "中" => { grade: 1, freq: 21, radical: "丨", on: [ "ちゅう" ], kun: [ "なか" ], meaning: "middle, inside" },
  "上" => { grade: 1, freq: 22, radical: "一", on: [ "じょう" ], kun: [ "うえ", "あ" ], meaning: "up, above" },
  "下" => { grade: 1, freq: 23, radical: "一", on: [ "か", "げ" ], kun: [ "した", "さ" ], meaning: "down, below" },
  "本" => { grade: 1, freq: 24, radical: "木", on: [ "ほん" ], kun: [ "もと" ], meaning: "book, origin" },
  "学" => { grade: 1, freq: 25, radical: "子", on: [ "がく" ], kun: [ "まな" ], meaning: "study, learn" },
  "生" => { grade: 1, freq: 26, radical: "生", on: [ "せい", "しょう" ], kun: [ "い", "う" ], meaning: "life, birth" },
  "先" => { grade: 1, freq: 27, radical: "儿", on: [ "せん" ], kun: [ "さき" ], meaning: "before, ahead" },
  "天" => { grade: 1, freq: 28, radical: "大", on: [ "てん" ], kun: [ "あま" ], meaning: "heaven, sky" },
  "気" => { grade: 1, freq: 29, radical: "气", on: [ "き", "け" ], kun: [], meaning: "spirit, energy" },
  "何" => { grade: 1, freq: 30, radical: "人", on: [ "か" ], kun: [ "なに", "なん" ], meaning: "what" },
  "私" => { grade: 1, freq: 31, radical: "禾", on: [ "し" ], kun: [ "わたし" ], meaning: "private, I" },
  "行" => { grade: 2, freq: 32, radical: "行", on: [ "こう", "ぎょう" ], kun: [ "い", "おこな" ], meaning: "go, conduct" },
  "来" => { grade: 2, freq: 33, radical: "木", on: [ "らい" ], kun: [ "く", "こ" ], meaning: "come" },
  "食" => { grade: 2, freq: 34, radical: "食", on: [ "しょく" ], kun: [ "た", "く" ], meaning: "eat, food" },
  "飲" => { grade: 3, freq: 35, radical: "食", on: [ "いん" ], kun: [ "の" ], meaning: "drink" },
  "見" => { grade: 1, freq: 36, radical: "見", on: [ "けん" ], kun: [ "み" ], meaning: "see, look" },
  "聞" => { grade: 2, freq: 37, radical: "門", on: [ "ぶん", "もん" ], kun: [ "き" ], meaning: "hear, ask" },
  "話" => { grade: 2, freq: 38, radical: "言", on: [ "わ" ], kun: [ "はな", "はなし" ], meaning: "talk, story" },
  "読" => { grade: 2, freq: 39, radical: "言", on: [ "どく" ], kun: [ "よ" ], meaning: "read" },
  "書" => { grade: 2, freq: 40, radical: "曰", on: [ "しょ" ], kun: [ "か" ], meaning: "write" },
  "買" => { grade: 2, freq: 41, radical: "貝", on: [ "ばい" ], kun: [ "か" ], meaning: "buy" },
  "帰" => { grade: 2, freq: 42, radical: "止", on: [ "き" ], kun: [ "かえ" ], meaning: "return home" },
  "待" => { grade: 3, freq: 43, radical: "彳", on: [ "たい" ], kun: [ "ま" ], meaning: "wait" },
  "持" => { grade: 3, freq: 44, radical: "手", on: [ "じ" ], kun: [ "も" ], meaning: "hold, have" },
  "決" => { grade: 3, freq: 45, radical: "水", on: [ "けつ" ], kun: [ "き" ], meaning: "decide" },
  "定" => { grade: 3, freq: 46, radical: "宀", on: [ "てい", "じょう" ], kun: [ "さだ" ], meaning: "fix, establish" },
  "必" => { grade: 4, freq: 47, radical: "心", on: [ "ひつ" ], kun: [ "かなら" ], meaning: "certain, necessary" },
  "要" => { grade: 4, freq: 48, radical: "襾", on: [ "よう" ], kun: [ "い" ], meaning: "need, essential" },
  "思" => { grade: 2, freq: 49, radical: "心", on: [ "し" ], kun: [ "おも" ], meaning: "think" },
  "言" => { grade: 2, freq: 50, radical: "言", on: [ "げん", "ごん" ], kun: [ "い", "こと" ], meaning: "say, word" },
  "時" => { grade: 2, freq: 51, radical: "日", on: [ "じ" ], kun: [ "とき" ], meaning: "time, hour" },
  "間" => { grade: 2, freq: 52, radical: "門", on: [ "かん", "けん" ], kun: [ "あいだ", "ま" ], meaning: "interval, between" },
  "今" => { grade: 2, freq: 53, radical: "人", on: [ "こん", "きん" ], kun: [ "いま" ], meaning: "now" },
  "明" => { grade: 2, freq: 54, radical: "日", on: [ "めい" ], kun: [ "あか", "あ" ], meaning: "bright, clear" },
  "前" => { grade: 2, freq: 55, radical: "刂", on: [ "ぜん" ], kun: [ "まえ" ], meaning: "before, front" },
  "後" => { grade: 2, freq: 56, radical: "彳", on: [ "ご", "こう" ], kun: [ "あと", "うし" ], meaning: "after, behind" },
  "友" => { grade: 2, freq: 57, radical: "又", on: [ "ゆう" ], kun: [ "とも" ], meaning: "friend" },
  "家" => { grade: 2, freq: 58, radical: "宀", on: [ "か", "け" ], kun: [ "いえ", "や" ], meaning: "house, home" },
  "国" => { grade: 2, freq: 59, radical: "囗", on: [ "こく" ], kun: [ "くに" ], meaning: "country" },
  "会" => { grade: 2, freq: 60, radical: "人", on: [ "かい" ], kun: [ "あ" ], meaning: "meet, meeting" },
  "物" => { grade: 3, freq: 61, radical: "牛", on: [ "ぶつ", "もつ" ], kun: [ "もの" ], meaning: "thing, object" },
  "語" => { grade: 2, freq: 62, radical: "言", on: [ "ご" ], kun: [ "かた" ], meaning: "language, word" },
  "電" => { grade: 2, freq: 63, radical: "雨", on: [ "でん" ], kun: [], meaning: "electricity" },
  "車" => { grade: 1, freq: 64, radical: "車", on: [ "しゃ" ], kun: [ "くるま" ], meaning: "car, vehicle" },
  "地" => { grade: 2, freq: 65, radical: "土", on: [ "ち", "じ" ], kun: [], meaning: "ground, earth" },
  "道" => { grade: 2, freq: 66, radical: "辶", on: [ "どう" ], kun: [ "みち" ], meaning: "road, way" },
  "新" => { grade: 2, freq: 67, radical: "斤", on: [ "しん" ], kun: [ "あたら" ], meaning: "new" },
  "仕" => { grade: 3, freq: 68, radical: "人", on: [ "し" ], kun: [ "つか" ], meaning: "serve, do" },
  "事" => { grade: 3, freq: 69, radical: "亅", on: [ "じ", "ず" ], kun: [ "こと" ], meaning: "thing, matter" },
  "勉" => { grade: 3, freq: 70, radical: "力", on: [ "べん" ], kun: [], meaning: "endeavor, study" },
  "強" => { grade: 2, freq: 71, radical: "弓", on: [ "きょう", "ごう" ], kun: [ "つよ" ], meaning: "strong" },
  "映" => { grade: 6, freq: 72, radical: "日", on: [ "えい" ], kun: [ "うつ" ], meaning: "reflect, project" },
  "画" => { grade: 2, freq: 73, radical: "田", on: [ "が", "かく" ], kun: [], meaning: "picture, plan" },
  "料" => { grade: 4, freq: 74, radical: "斗", on: [ "りょう" ], kun: [], meaning: "fee, material" },
  "理" => { grade: 2, freq: 75, radical: "王", on: [ "り" ], kun: [], meaning: "reason, logic" },
  "音" => { grade: 1, freq: 76, radical: "音", on: [ "おん" ], kun: [ "おと", "ね" ], meaning: "sound" },
  "楽" => { grade: 2, freq: 77, radical: "木", on: [ "がく", "らく" ], kun: [ "たの" ], meaning: "music, comfort" },
  "場" => { grade: 2, freq: 78, radical: "土", on: [ "じょう" ], kun: [ "ば" ], meaning: "place, location" },
  "所" => { grade: 3, freq: 79, radical: "户", on: [ "しょ" ], kun: [ "ところ" ], meaning: "place" },
  "飯" => { grade: 4, freq: 80, radical: "食", on: [ "はん" ], kun: [ "めし" ], meaning: "meal, rice" },
  "朝" => { grade: 2, freq: 81, radical: "月", on: [ "ちょう" ], kun: [ "あさ" ], meaning: "morning" },
  "昼" => { grade: 2, freq: 82, radical: "日", on: [ "ちゅう" ], kun: [ "ひる" ], meaning: "daytime, noon" },
  "晩" => { grade: 6, freq: 83, radical: "日", on: [ "ばん" ], kun: [], meaning: "evening, night" },
  "英" => { grade: 4, freq: 84, radical: "艹", on: [ "えい" ], kun: [], meaning: "excellent, English" },
  "人" => { grade: 1, freq: 85, radical: "人", on: [ "じん", "にん" ], kun: [ "ひと" ], meaning: "person" },
  "校" => { grade: 1, freq: 86, radical: "木", on: [ "こう" ], kun: [], meaning: "school" },
  "毎" => { grade: 2, freq: 87, radical: "毋", on: [ "まい" ], kun: [], meaning: "every" },
  "駅" => { grade: 3, freq: 88, radical: "馬", on: [ "えき" ], kun: [], meaning: "station" },
  "真" => { grade: 3, freq: 89, radical: "目", on: [ "しん" ], kun: [ "ま" ], meaning: "true, reality" },
  "紙" => { grade: 2, freq: 90, radical: "糸", on: [ "し" ], kun: [ "かみ" ], meaning: "paper" },
  "元" => { grade: 2, freq: 91, radical: "儿", on: [ "げん", "がん" ], kun: [ "もと" ], meaning: "origin, vitality" },
  "鉄" => { grade: 3, freq: 92, radical: "金", on: [ "てつ" ], kun: [], meaning: "iron, steel" },
  "週" => { grade: 2, freq: 93, radical: "辶", on: [ "しゅう" ], kun: [], meaning: "week" },
  "昨" => { grade: 4, freq: 94, radical: "日", on: [ "さく" ], kun: [ "きの" ], meaning: "yesterday, previous" },
  "曜" => { grade: 2, freq: 95, radical: "日", on: [ "よう" ], kun: [], meaning: "weekday" },
  "達" => { grade: 4, freq: 96, radical: "辶", on: [ "たつ" ], kun: [ "たち" ], meaning: "reach, attain" },
  "族" => { grade: 3, freq: 97, radical: "方", on: [ "ぞく" ], kun: [], meaning: "family, tribe" },
  "方" => { grade: 2, freq: 98, radical: "方", on: [ "ほう" ], kun: [ "かた" ], meaning: "direction, way" },
  "世" => { grade: 3, freq: 99, radical: "一", on: [ "せ", "せい" ], kun: [ "よ" ], meaning: "world, generation" },
  "界" => { grade: 3, freq: 100, radical: "田", on: [ "かい" ], kun: [], meaning: "boundary, world" },
  "写" => { grade: 3, freq: 101, radical: "冖", on: [ "しゃ" ], kun: [ "うつ" ], meaning: "copy, photograph" },
  "手" => { grade: 1, freq: 102, radical: "手", on: [ "しゅ" ], kun: [ "て" ], meaning: "hand" },
  "葉" => { grade: 3, freq: 103, radical: "艹", on: [ "よう" ], kun: [ "は" ], meaning: "leaf" },
  "開" => { grade: 3, freq: 104, radical: "門", on: [ "かい" ], kun: [ "あ", "ひら" ], meaning: "open" },
  "高" => { grade: 2, freq: 105, radical: "高", on: [ "こう" ], kun: [ "たか" ], meaning: "tall, high, expensive" },
  "切" => { grade: 2, freq: 106, radical: "刀", on: [ "せつ", "さい" ], kun: [ "き" ], meaning: "cut, important" },
  "心" => { grade: 2, freq: 107, radical: "心", on: [ "しん" ], kun: [ "こころ" ], meaning: "heart, mind" }
}.freeze

# Words: surface => { reading, meaning, jlpt, freq, pos }
WORDS = {
  # numbers
  "一つ" => { reading: "ひとつ", meaning: "one thing", jlpt: "N5", freq: 1, pos: "noun" },
  "二人" => { reading: "ふたり", meaning: "two people", jlpt: "N5", freq: 2, pos: "noun" },
  "三人" => { reading: "さんにん", meaning: "three people", jlpt: "N5", freq: 3, pos: "noun" },
  "十日" => { reading: "とおか", meaning: "ten days, tenth day", jlpt: "N4", freq: 4, pos: "noun" },
  # time / calendar
  "今日" => { reading: "きょう", meaning: "today", jlpt: "N5", freq: 5, pos: "noun" },
  "明日" => { reading: "あした", meaning: "tomorrow", jlpt: "N5", freq: 6, pos: "noun" },
  "昨日" => { reading: "きのう", meaning: "yesterday", jlpt: "N5", freq: 7, pos: "noun" },
  "今年" => { reading: "ことし", meaning: "this year", jlpt: "N5", freq: 8, pos: "noun" },
  "毎日" => { reading: "まいにち", meaning: "every day", jlpt: "N5", freq: 9, pos: "noun" },
  "時間" => { reading: "じかん", meaning: "time", jlpt: "N5", freq: 10, pos: "noun" },
  "月曜日" => { reading: "げつようび", meaning: "Monday", jlpt: "N5", freq: 11, pos: "noun" },
  "火曜日" => { reading: "かようび", meaning: "Tuesday", jlpt: "N5", freq: 12, pos: "noun" },
  "水曜日" => { reading: "すいようび", meaning: "Wednesday", jlpt: "N5", freq: 13, pos: "noun" },
  "木曜日" => { reading: "もくようび", meaning: "Thursday", jlpt: "N5", freq: 14, pos: "noun" },
  "金曜日" => { reading: "きんようび", meaning: "Friday", jlpt: "N5", freq: 15, pos: "noun" },
  "土曜日" => { reading: "どようび", meaning: "Saturday", jlpt: "N5", freq: 16, pos: "noun" },
  "日曜日" => { reading: "にちようび", meaning: "Sunday", jlpt: "N5", freq: 17, pos: "noun" },
  "今朝" => { reading: "けさ", meaning: "this morning", jlpt: "N4", freq: 18, pos: "noun" },
  "今晩" => { reading: "こんばん", meaning: "this evening", jlpt: "N4", freq: 19, pos: "noun" },
  "昼間" => { reading: "ひるま", meaning: "daytime", jlpt: "N4", freq: 20, pos: "noun" },
  # people / life
  "私" => { reading: "わたし", meaning: "I, me", jlpt: "N5", freq: 21, pos: "pronoun" },
  "先生" => { reading: "せんせい", meaning: "teacher", jlpt: "N5", freq: 22, pos: "noun" },
  "学生" => { reading: "がくせい", meaning: "student", jlpt: "N5", freq: 23, pos: "noun" },
  "友人" => { reading: "ゆうじん", meaning: "friend", jlpt: "N4", freq: 24, pos: "noun" },
  "友達" => { reading: "ともだち", meaning: "friend", jlpt: "N5", freq: 25, pos: "noun" },
  "家族" => { reading: "かぞく", meaning: "family", jlpt: "N5", freq: 26, pos: "noun" },
  "一人" => { reading: "ひとり", meaning: "one person, alone", jlpt: "N5", freq: 27, pos: "noun" },
  "人生" => { reading: "じんせい", meaning: "life (of a person)", jlpt: "N4", freq: 28, pos: "noun" },
  "先生方" => { reading: "せんせいがた", meaning: "teachers (plural)", jlpt: "N4", freq: 29, pos: "noun" },
  # places / world
  "日本" => { reading: "にほん", meaning: "Japan", jlpt: "N5", freq: 30, pos: "noun" },
  "家" => { reading: "いえ", meaning: "house, home", jlpt: "N5", freq: 31, pos: "noun" },
  "国" => { reading: "くに", meaning: "country", jlpt: "N5", freq: 32, pos: "noun" },
  "世界" => { reading: "せかい", meaning: "world", jlpt: "N4", freq: 33, pos: "noun" },
  "場所" => { reading: "ばしょ", meaning: "place, location", jlpt: "N4", freq: 34, pos: "noun" },
  "大学" => { reading: "だいがく", meaning: "university", jlpt: "N5", freq: 35, pos: "noun" },
  "学校" => { reading: "がっこう", meaning: "school", jlpt: "N5", freq: 36, pos: "noun" },
  "道" => { reading: "みち", meaning: "road, way", jlpt: "N4", freq: 37, pos: "noun" },
  "地下鉄" => { reading: "ちかてつ", meaning: "subway", jlpt: "N4", freq: 38, pos: "noun" },
  "電車" => { reading: "でんしゃ", meaning: "train", jlpt: "N5", freq: 39, pos: "noun" },
  "駅" => { reading: "えき", meaning: "station", jlpt: "N5", freq: 40, pos: "noun" },
  # things / objects
  "本" => { reading: "ほん", meaning: "book", jlpt: "N5", freq: 41, pos: "noun" },
  "物" => { reading: "もの", meaning: "thing", jlpt: "N4", freq: 42, pos: "noun" },
  "食べ物" => { reading: "たべもの", meaning: "food", jlpt: "N5", freq: 43, pos: "noun" },
  "飲み物" => { reading: "のみもの", meaning: "drink", jlpt: "N5", freq: 44, pos: "noun" },
  "買い物" => { reading: "かいもの", meaning: "shopping", jlpt: "N5", freq: 45, pos: "noun" },
  "電話" => { reading: "でんわ", meaning: "telephone, phone call", jlpt: "N5", freq: 46, pos: "noun" },
  "写真" => { reading: "しゃしん", meaning: "photograph", jlpt: "N5", freq: 47, pos: "noun" },
  "音楽" => { reading: "おんがく", meaning: "music", jlpt: "N4", freq: 48, pos: "noun" },
  "映画" => { reading: "えいが", meaning: "movie, film", jlpt: "N4", freq: 49, pos: "noun" },
  "料理" => { reading: "りょうり", meaning: "cooking, cuisine", jlpt: "N4", freq: 50, pos: "noun" },
  "手紙" => { reading: "てがみ", meaning: "letter", jlpt: "N4", freq: 51, pos: "noun" },
  "言葉" => { reading: "ことば", meaning: "word, language", jlpt: "N4", freq: 52, pos: "noun" },
  "日本語" => { reading: "にほんご", meaning: "Japanese language", jlpt: "N5", freq: 53, pos: "noun" },
  "英語" => { reading: "えいご", meaning: "English language", jlpt: "N5", freq: 54, pos: "noun" },
  # food
  "朝ご飯" => { reading: "あさごはん", meaning: "breakfast", jlpt: "N5", freq: 55, pos: "noun" },
  "昼ご飯" => { reading: "ひるごはん", meaning: "lunch", jlpt: "N5", freq: 56, pos: "noun" },
  "晩ご飯" => { reading: "ばんごはん", meaning: "dinner", jlpt: "N5", freq: 57, pos: "noun" },
  "水" => { reading: "みず", meaning: "water", jlpt: "N5", freq: 58, pos: "noun" },
  "ご飯" => { reading: "ごはん", meaning: "rice, meal", jlpt: "N5", freq: 59, pos: "noun" },
  # verbs
  "行く" => { reading: "いく", meaning: "to go", jlpt: "N5", freq: 60, pos: "verb" },
  "来る" => { reading: "くる", meaning: "to come", jlpt: "N5", freq: 61, pos: "verb" },
  "食べる" => { reading: "たべる", meaning: "to eat", jlpt: "N5", freq: 62, pos: "verb" },
  "飲む" => { reading: "のむ", meaning: "to drink", jlpt: "N5", freq: 63, pos: "verb" },
  "見る" => { reading: "みる", meaning: "to see, to watch", jlpt: "N5", freq: 64, pos: "verb" },
  "聞く" => { reading: "きく", meaning: "to hear, to listen", jlpt: "N5", freq: 65, pos: "verb" },
  "話す" => { reading: "はなす", meaning: "to speak, to talk", jlpt: "N5", freq: 66, pos: "verb" },
  "読む" => { reading: "よむ", meaning: "to read", jlpt: "N5", freq: 67, pos: "verb" },
  "書く" => { reading: "かく", meaning: "to write", jlpt: "N5", freq: 68, pos: "verb" },
  "買う" => { reading: "かう", meaning: "to buy", jlpt: "N5", freq: 69, pos: "verb" },
  "帰る" => { reading: "かえる", meaning: "to return home", jlpt: "N5", freq: 70, pos: "verb" },
  "待つ" => { reading: "まつ", meaning: "to wait", jlpt: "N4", freq: 71, pos: "verb" },
  "持つ" => { reading: "もつ", meaning: "to hold, to have", jlpt: "N4", freq: 72, pos: "verb" },
  "決める" => { reading: "きめる", meaning: "to decide", jlpt: "N4", freq: 73, pos: "verb" },
  "決まる" => { reading: "きまる", meaning: "to be decided", jlpt: "N4", freq: 74, pos: "verb" },
  "思う" => { reading: "おもう", meaning: "to think", jlpt: "N4", freq: 75, pos: "verb" },
  "言う" => { reading: "いう", meaning: "to say", jlpt: "N5", freq: 76, pos: "verb" },
  "生まれる" => { reading: "うまれる", meaning: "to be born", jlpt: "N4", freq: 77, pos: "verb" },
  "開く" => { reading: "あく", meaning: "to open", jlpt: "N4", freq: 78, pos: "verb" },
  "会う" => { reading: "あう", meaning: "to meet", jlpt: "N5", freq: 79, pos: "verb" },
  "行き方" => { reading: "いきかた", meaning: "way of going", jlpt: "N4", freq: 80, pos: "noun" },
  # adjectives / adverbs
  "大きい" => { reading: "おおきい", meaning: "big, large", jlpt: "N5", freq: 81, pos: "adjective" },
  "小さい" => { reading: "ちいさい", meaning: "small, little", jlpt: "N5", freq: 82, pos: "adjective" },
  "新しい" => { reading: "あたらしい", meaning: "new", jlpt: "N5", freq: 83, pos: "adjective" },
  "強い" => { reading: "つよい", meaning: "strong", jlpt: "N4", freq: 84, pos: "adjective" },
  "高い" => { reading: "たかい", meaning: "high, expensive", jlpt: "N5", freq: 85, pos: "adjective" },
  "必ず" => { reading: "かならず", meaning: "certainly, without fail", jlpt: "N4", freq: 86, pos: "adverb" },
  # compounds (kanji meaning is the difficult part)
  "必要" => { reading: "ひつよう", meaning: "necessary, required", jlpt: "N4", freq: 87, pos: "noun" },
  "大切" => { reading: "たいせつ", meaning: "important, precious", jlpt: "N4", freq: 88, pos: "adjective" },
  "決定" => { reading: "けってい", meaning: "decision", jlpt: "N3", freq: 89, pos: "noun" },
  "決心" => { reading: "けっしん", meaning: "determination, resolution", jlpt: "N3", freq: 90, pos: "noun" },
  "定年" => { reading: "ていねん", meaning: "retirement age", jlpt: "N3", freq: 91, pos: "noun" },
  "勉強" => { reading: "べんきょう", meaning: "study", jlpt: "N5", freq: 92, pos: "noun" },
  "仕事先" => { reading: "しごとさき", meaning: "place of work", jlpt: "N4", freq: 93, pos: "noun" },
  "仕事" => { reading: "しごと", meaning: "work, job", jlpt: "N5", freq: 94, pos: "noun" },
  "先週" => { reading: "せんしゅう", meaning: "last week", jlpt: "N5", freq: 95, pos: "noun" },
  "来週" => { reading: "らいしゅう", meaning: "next week", jlpt: "N5", freq: 96, pos: "noun" },
  "今週" => { reading: "こんしゅう", meaning: "this week", jlpt: "N5", freq: 97, pos: "noun" },
  "来月" => { reading: "らいげつ", meaning: "next month", jlpt: "N5", freq: 98, pos: "noun" },
  "先月" => { reading: "せんげつ", meaning: "last month", jlpt: "N5", freq: 99, pos: "noun" },
  "毎週" => { reading: "まいしゅう", meaning: "every week", jlpt: "N4", freq: 100, pos: "noun" },
  "後で" => { reading: "あとで", meaning: "later", jlpt: "N5", freq: 101, pos: "adverb" },
  "後ろ" => { reading: "うしろ", meaning: "behind, back", jlpt: "N5", freq: 102, pos: "noun" },
  "前" => { reading: "まえ", meaning: "before, front", jlpt: "N5", freq: 103, pos: "noun" },
  "明るい" => { reading: "あかるい", meaning: "bright, cheerful", jlpt: "N4", freq: 104, pos: "adjective" },
  "天気" => { reading: "てんき", meaning: "weather", jlpt: "N5", freq: 105, pos: "noun" },
  "元気" => { reading: "げんき", meaning: "healthy, energetic", jlpt: "N5", freq: 106, pos: "noun" },
  "気持ち" => { reading: "きもち", meaning: "feeling, mood", jlpt: "N4", freq: 107, pos: "noun" },
  "何" => { reading: "なに", meaning: "what", jlpt: "N5", freq: 108, pos: "pronoun" },
  "何時" => { reading: "なんじ", meaning: "what time", jlpt: "N5", freq: 109, pos: "noun" },
  "何曜日" => { reading: "なんようび", meaning: "what day of the week", jlpt: "N5", freq: 110, pos: "noun" },
  "何人" => { reading: "なんにん", meaning: "how many people", jlpt: "N5", freq: 111, pos: "noun" }
}.freeze

# Sentences: [japanese, translation]. Curated, natural Japanese; each contains at
# least one of the words above so the corpus actually exercises the question engine.
SENTENCES = [
  [ "今日は天気がいいですね。", "The weather is nice today, isn't it?" ],
  [ "明日は朝から忙しいです。", "I will be busy from tomorrow morning." ],
  [ "昨日は友達と映画を見ました。", "Yesterday I watched a movie with a friend." ],
  [ "毎日日本語を勉強しています。", "I study Japanese every day." ],
  [ "毎朝コーヒーを飲みます。", "I drink coffee every morning." ],
  [ "今週は時間がありません。", "I have no time this week." ],
  [ "先週の金曜日に日本へ行きました。", "I went to Japan last Friday." ],
  [ "来月は家族と会います。", "I will meet my family next month." ],
  [ "今日は学校へ行きません。", "I won't go to school today." ],
  [ "駅まで地下鉄で行きます。", "I go to the station by subway." ],
  [ "電車の中で本を読みました。", "I read a book on the train." ],
  [ "友達は大学で英語を教えています。", "My friend teaches English at a university." ],
  [ "先生は新しい言葉を説明しました。", "The teacher explained the new words." ],
  [ "家の近くに大きい本屋があります。", "There is a big bookstore near my house." ],
  [ "毎晩ご飯の後に散歩します。", "I take a walk after dinner every evening." ],
  [ "朝ご飯は食べませんでした。", "I didn't eat breakfast." ],
  [ "昼ご飯は会社で食べます。", "I eat lunch at the office." ],
  [ "晩ご飯は家族と一緒に食べます。", "I eat dinner with my family." ],
  [ "水を一杯ください。", "Please give me a glass of water." ],
  [ "この店の料理はとてもおいしいです。", "The food at this restaurant is very delicious." ],
  [ "今日の音楽の授業は楽しかったです。", "Today's music class was enjoyable." ],
  [ "新しい映画を一緒に見に行きませんか。", "Why don't we go watch the new movie together?" ],
  [ "写真を一枚見せてください。", "Please show me one photo." ],
  [ "母に手紙を書きました。", "I wrote a letter to my mother." ],
  [ "何時にお店が開きますか。", "What time does the store open?" ],
  [ "日本語の本を一冊読みました。", "I read one Japanese book." ],
  [ "英語の会話を練習しています。", "I am practicing English conversation." ],
  [ "電車がもうすぐ来ます。", "The train will come soon." ],
  [ "来年の春に日本へ行きたいです。", "I want to go to Japan next spring." ],
  [ "去年の冬はとても寒かったです。", "Last winter was very cold." ],
  [ "今日は何を食べたいですか。", "What do you want to eat today?" ],
  [ "明日は何時に行きますか。", "What time are you going tomorrow?" ],
  [ "今日は何曜日ですか。", "What day of the week is it today?" ],
  [ "家族は何人ですか。", "How many people are in your family?" ],
  [ "毎週日曜日に公園へ行きます。", "I go to the park every Sunday." ],
  [ "火曜日は会議があります。", "There is a meeting on Tuesday." ],
  [ "水曜日の午後に病院へ行きます。", "I will go to the hospital on Wednesday afternoon." ],
  [ "木曜日に買い物に行きましょう。", "Let's go shopping on Thursday." ],
  [ "金曜日の夜は友達と飲みに行きます。", "On Friday night I go drinking with friends." ],
  [ "土曜日は家でゆっくりします。", "On Saturday I relax at home." ],
  [ "月曜日に大事な試験があります。", "I have an important exam on Monday." ],
  [ "昨日は一日中家にいました。", "Yesterday I stayed home all day." ],
  [ "今日は一人で昼ご飯を食べました。", "I ate lunch alone today." ],
  [ "先週新しい本を買いました。", "I bought a new book last week." ],
  [ "この道をまっすぐ行ってください。", "Please go straight down this road." ],
  [ "駅の前に店があります。", "There is a shop in front of the station." ],
  [ "学校の後で友達に会います。", "I will meet a friend after school." ],
  [ "学生は図書館で勉強します。", "Students study in the library." ],
  [ "先生の話を聞いてください。", "Please listen to the teacher." ],
  [ "彼は毎日仕事に電車で行きます。", "He goes to work by train every day." ],
  [ "仕事の後で一杯飲みませんか。", "How about a drink after work?" ],
  [ "日本では電車がとても便利です。", "Trains are very convenient in Japan." ],
  [ "世界にはいろいろな言葉があります。", "There are many different languages in the world." ],
  [ "日本語の言葉をたくさん覚えたいです。", "I want to learn many Japanese words." ],
  [ "友達の家で晩ご飯を食べました。", "I ate dinner at my friend's house." ],
  [ "家族と一緒に旅行に行きます。", "I will go on a trip with my family." ],
  [ "一人で生活しています。", "I live alone." ],
  [ "人生は一度だけです。", "You only live once." ],
  [ "この本はとても面白いです。", "This book is very interesting." ],
  [ "何を言ったか聞こえませんでした。", "I couldn't hear what you said." ],
  [ "もう一度言ってください。", "Please say it once more." ],
  [ "彼女は明るくて元気な人です。", "She is a bright and energetic person." ],
  [ "今日は気持ちがいい天気ですね。", "Today is a pleasant day." ],
  [ "必ず時間を守ってください。", "Please be sure to be on time." ],
  [ "これは私の大切な物です。", "This is my precious thing." ],
  [ "決心したことは必ずやりましょう。", "Do whatever you've decided on, without fail." ],
  [ "決定を後で連絡します。", "I will contact you with the decision later." ],
  [ "明日までに決めなければなりません。", "I have to decide by tomorrow." ],
  [ "どこに行くかまだ決めていません。", "I haven't decided where to go yet." ],
  [ "行き先が決まったら教えてください。", "Let me know once the destination is decided." ],
  [ "会議の日時は後で決まります。", "The meeting time will be decided later." ],
  [ "決める前に話を聞いてください。", "Please listen before deciding." ],
  [ "彼は必ず成功すると信じています。", "I believe he will surely succeed." ],
  [ "体に必要な水を飲みましょう。", "Let's drink the water your body needs." ],
  [ "必要な物は何でも言ってください。", "Tell me whatever you need." ],
  [ "事故がなくて何よりです。", "The best thing is that there was no accident." ],
  [ "この仕事は強い体が必要です。", "This job requires a strong body." ],
  [ "新しくて大きい家を買いました。", "I bought a new, large house." ],
  [ "昨日買った物を返しました。", "I returned the thing I bought yesterday." ],
  [ "買い物は明日にします。", "I'll do the shopping tomorrow." ],
  [ "電車を待っています。", "I'm waiting for the train." ],
  [ "ちょっと待ってください。", "Please wait a moment." ],
  [ "先生は本を持っています。", "The teacher has a book." ],
  [ "財布を持って来るのを忘れました。", "I forgot to bring my wallet." ],
  [ "私は毎日手帳を持っています。", "I carry a notebook every day." ],
  [ "家に帰ってからご飯を食べます。", "I'll eat after I get home." ],
  [ "帰る前に飲み物を買います。", "I'll buy a drink before going home." ],
  [ "今日は早く帰りたいです。", "I want to go home early today." ],
  [ "聞いた話をそのまま言いました。", "I repeated the story just as I heard it." ],
  [ "その言葉は使い方が難しいです。", "That word is hard to use." ],
  [ "毎日新しい言葉を覚えます。", "I memorize new words every day." ],
  [ "何を読んでいますか。", "What are you reading?" ],
  [ "新聞を読むのが好きです。", "I like reading the newspaper." ],
  [ "日本語を読む練習をしています。", "I'm practicing reading Japanese." ],
  [ "朝早く起きて本を読みました。", "I woke up early and read in the morning." ],
  [ "彼は何も言いませんでした。", "He didn't say anything." ],
  [ "大きい声で話してください。", "Please speak in a loud voice." ],
  [ "英語で話してもいいですか。", "May I speak in English?" ],
  [ "日本語で話しましょう。", "Let's talk in Japanese." ],
  [ "小さな声で話しています。", "They are speaking in a low voice." ],
  [ "本を買うお金がありません。", "I don't have money to buy books." ],
  [ "この店は何時に閉まりますか。", "What time does this shop close?" ],
  [ "駅の改札で待っています。", "I'm waiting at the station gate." ],
  [ "後で電話しますね。", "I'll call you later." ],
  [ "後ろの席に座ってください。", "Please sit in the back seat." ],
  [ "前の方で見てください。", "Please watch from the front." ],
  [ "会議は前の日に行われます。", "The meeting is held the day before." ],
  [ "生まれてからずっと日本に住んでいます。", "I've lived in Japan since I was born." ],
  [ "娘が先月生まれました。", "My daughter was born last month." ],
  [ "先生に聞いてみましょう。", "Let's ask the teacher." ],
  [ "音楽を聞きながら勉強します。", "I study while listening to music." ],
  [ "映画を見てから寝ます。", "I'll sleep after watching a movie." ],
  [ "写真を見ながら話しましょう。", "Let's talk while looking at the photos." ],
  [ "毎朝七時に起きます。", "I wake up at seven every morning." ],
  [ "今日は七時に起きました。", "I woke up at seven today." ],
  [ "今朝は六時に起きました。", "I woke up at six this morning." ],
  [ "今晩は早く寝ます。", "I'll go to bed early tonight." ],
  [ "夜は十時に寝ます。", "I go to bed at ten at night." ],
  [ "午後は本を読みます。", "I'll read in the afternoon." ],
  [ "時間がまだあります。", "There's still time." ],
  [ "時間がないから早く行きます。", "I'll go quickly because there's no time." ],
  [ "間を空けて席に座ってください。", "Please sit leaving a space between you." ],
  [ "あいだに何か食べませんか。", "Shall we eat something in between?" ],
  [ "今年は暖かい冬です。", "This year has been a warm winter." ],
  [ "来年は日本で仕事をします。", "I'll work in Japan next year." ],
  [ "去年買った靴が壊れました。", "The shoes I bought last year broke." ],
  [ "十日間の旅行に行きました。", "I went on a ten-day trip." ],
  [ "二人で一杯飲みに行きました。", "The two of us went out for a drink." ],
  [ "三人で一つの部屋に住んでいます。", "Three of us live in one room." ],
  [ "一つだけ選んでください。", "Please choose just one." ],
  [ "水曜日にまた会いましょう。", "Let's meet again on Wednesday." ],
  [ "毎日日本語で話します。", "I speak Japanese every day." ],
  [ "あの高い建物は何ですか。", "What is that tall building?" ],
  [ "強い雨が降っています。", "It is raining hard." ],
  [ "新しい仕事を始めました。", "I started a new job." ],
  [ "仕事の場所は駅から近いです。", "My workplace is close to the station." ],
  [ "仕事先で日本人の友達ができました。", "I made Japanese friends at work." ],
  [ "この料理はとても上手です。", "This cooking is very skillful." ],
  [ "料理の本を一冊買いました。", "I bought a cookbook." ],
  [ "英語の音楽が好きです。", "I like English music." ],
  [ "音楽の時間が一番好きです。", "Music class is my favorite." ],
  [ "この映画は有名です。", "This movie is famous." ],
  [ "映画館はこの場所にあります。", "The movie theater is in this place." ],
  [ "道を間違えてしまいました。", "I took the wrong road." ],
  [ "道で先生に会いました。", "I met my teacher on the road." ],
  [ "国の生活は楽しいです。", "Life in my country is enjoyable." ],
  [ "国に帰りたいと思っています。", "I'm thinking I want to return to my country." ],
  [ "日本はお茶の国です。", "Japan is a country of tea." ],
  [ "世界のニュースを見ます。", "I watch world news." ],
  [ "世界中の人がこの歌を知っています。", "People all over the world know this song." ],
  [ "私の家は駅から遠いです。", "My house is far from the station." ],
  [ "私の名前は田中です。", "My name is Tanaka." ],
  [ "明日は私の誕生日です。", "Tomorrow is my birthday." ],
  [ "その店の場所を教えてください。", "Please tell me the location of that shop." ],
  [ "食べ物は何でも好きです。", "I like any food." ],
  [ "飲み物は何にしますか。", "What would you like to drink?" ],
  [ "この本は十時までに返してください。", "Please return this book by ten o'clock." ],
  [ "一日中何も食べませんでした。", "I didn't eat anything all day." ],
  [ "何年ここに住んでいますか。", "How many years have you lived here?" ],
  [ "十年前にこの家を買いました。", "I bought this house ten years ago." ],
  [ "毎年夏に海へ行きます。", "I go to the sea every summer." ],
  [ "毎年新しい目標を決めます。", "I set a new goal every year." ],
  [ "今年の目標を決めました。", "I've decided on this year's goal." ],
  [ "明日までに決めてください。", "Please decide by tomorrow." ],
  [ "決定が早くて驚きました。", "I was surprised by how quick the decision was." ],
  [ "決心が変わってしまいました。", "My resolution has changed." ],
  [ "定年まで働くつもりです。", "I intend to work until retirement age." ],
  [ "必ず連絡します。", "I will definitely contact you." ],
  [ "必ず来てくださいね。", "Please be sure to come." ],
  [ "この仕事は必ず終わらせます。", "I will definitely finish this work." ],
  [ "必要な物は全部買いました。", "I bought everything I needed." ],
  [ "彼女は大事な話があります。", "She has something important to say." ],
  [ "大切な時間を無駄にしないでください。", "Don't waste precious time." ],
  [ "何でも気軽に言ってください。", "Feel free to say anything." ],
  [ "思ったことを話してください。", "Please say what you think." ],
  [ "彼はいつも楽しい話をします。", "He always tells fun stories." ],
  [ "この言葉はどういう意味ですか。", "What does this word mean?" ],
  [ "言葉の意味を調べました。", "I looked up the meaning of the word." ],
  [ "日本語の本を読むのが好きです。", "I like reading Japanese books." ],
  [ "本を読む時間がありません。", "I don't have time to read books." ],
  [ "この本を読んでください。", "Please read this book." ],
  [ "本は何冊持っていますか。", "How many books do you have?" ],
  [ "新しい本を読んでいます。", "I'm reading a new book." ],
  [ "彼は毎晩本を読みます。", "He reads books every night." ],
  [ "この問題を考えています。", "I'm thinking about this problem." ],
  [ "何を考えているの。", "What are you thinking about?" ],
  [ "考えた後で返事します。", "I'll reply after I think about it." ],
  [ "いい考えがあります。", "I have a good idea." ],
  [ "言いたいことを紙に書きました。", "I wrote what I wanted to say on paper." ],
  [ "名前をここに書いてください。", "Please write your name here." ],
  [ "毎日日記を書いています。", "I write in my diary every day." ],
  [ "電話番号を書いてもらえますか。", "Can you write down your phone number?" ]
].freeze

puts "Seeding kanji..."
kanji_by_char = {}
KANJI.each do |character, data|
  next if data.nil?

  kanji = Kanji.find_or_initialize_by(character:)
  kanji.update!(
    grade: data[:grade],
    frequency_rank: data[:freq],
    radical_id: nil,
    meaning_summary: data[:meaning]
  )
  %w[onyomi kunyomi].each do |kind|
    Array(data[kind.to_sym]).each do |reading|
      kanji.readings.find_or_initialize_by(reading:, kind:).save!
    end
  end
  kanji_by_char[character] = kanji
end

puts "Seeding words..."
word_by_surface = {}
WORDS.each do |surface, data|
  word = Word.find_or_initialize_by(surface:)
  word.update!(
    reading: data[:reading],
    frequency_rank: data[:freq],
    jlpt_level: data[:jlpt],
    meaning: data[:meaning],
    part_of_speech: data[:pos]
  )

  word.kanji_surfaces.each_with_index do |char, index|
    kanji = kanji_by_char[char]
    raise "Seed error: kanji #{char} in word #{surface} is missing from KANJI" if kanji.nil?

    WordKanji.find_or_initialize_by(word:, kanji:).update!(position: index)
  end

  word_by_surface[surface] = word
end

puts "Seeding sentences..."
segmenter = Segmentation::LongestMatch.build(word_by_surface.keys)
SENTENCES.each do |japanese, translation|
  sentence = Sentence.find_or_initialize_by(japanese:, translation:)
  sentence.update!(difficulty: 3, source: "curated", external_id: "seed:#{japanese}")

  segmenter.segment(japanese).each do |token|
    word = word_by_surface[token.surface]
    next if word.nil?

    SentenceWord.find_or_create_by!(
      sentence:,
      word:,
      start_position: token.start_position,
      end_position: token.end_position
    )
  end
end

puts "Seeding demo user..."
user = User.find_or_create_by!(id: 1)
puts "Done. #{Kanji.count} kanji, #{Word.count} words, #{Sentence.count} sentences."
